<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMdm52hQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMdm52hQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMdm52hQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMdm52hQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMdm52hQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'Mdm52hQ',
    'container.build_id' => '430083f3',
    'container.build_time' => 1614249908,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMdm52hQ');
